name: nlplay
channels:
- defaults
- conda-forge
- anaconda
- pytorch
dependencies:
  - numpy=>1.17.4
  - pandas
  - python=3.7
  - pytorch
  - scikit-learn
  - pyarrow>=0.15.1
  - pip:
    - tqdm
    - git+https://github.com/facebookresearch/fastText.git
    - pytest
    - blingfire
    - beautifulsoup4
    - matplotlib
    - hyperopt
    - requests
    - PyYAML
    - matplotlib
    - keras_preprocessing
